#twitter_username: pbloemesquire
title_image: "lr.cs.vu.nl/images/Learning-and-Reasoning-logos0001.png"
description: Learning and reasoning research group at Vrije Universiteit Amsterdam
baseurl: https://lr.cs.vu.nl/
